Repository tmax-cloud/registry-operator, pull requests merged in 2021-03, with the labels that each got.

#116 [feat] Add dockerhub client API
  internal/common/auth/token.go
  internal/common/http/client.go
  pkg/registry/ext/dockerhub/api.go
  pkg/registry/ext/dockerhub/client.go
  pkg/registry/ext/dockerhub/types.go
  pkg/registry/ext/dockerhub/util.go
  pkg/registry/ext/dockerhub/util_test.go
Labels: type: feature

#117 [mod] Add image replicate handler
  api/v1/externalregistry_types.go
  api/v1/imagereplicate_types.go
  api/v1/registryjob_types.go
  config/crd/bases/tmax.io_externalregistries.yaml
  config/crd/bases/tmax.io_imagereplicates.yaml
  config/crd/bases/tmax.io_registrycronjobs.yaml
  config/crd/bases/tmax.io_registryjobs.yaml
  controllers/exregctl/handler/extreg_sync.go
  controllers/imagereplicate_controller.go
  controllers/replicatectl/handler/replicate.go
  internal/schemes/util.go
  main.go
  pkg/registry/ext/factory/sync.go
  pkg/registry/factory.go
  pkg/registry/replicate/copy.go
Labels: type: maintenance

#118 Fix/imagescanrequest spec
  api/v1/imagescanrequest_types.go
  config/crd/bases/tmax.io_imagescanrequests.yaml
  config/manager/manager_config.yaml
  config/manager/manager_dev.yaml
  controllers/imagescanrequest_controller.go
  docs/usage/imagescanrequest.md
  internal/common/config/env.go
  pkg/apiserver/apis/v1/scanrequest.go
  pkg/apiserver/apis/v1/scanresult.go
  pkg/scan/scan.go
  pkg/scan/scan_test.go
Labels: type: maintenance

#119 [mod] Implement ImageReplicate status
  api/v1/conditions.go
  api/v1/imagereplicate_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_imagereplicates.yaml
  controllers/imagereplicate_controller.go
  controllers/replicatectl/handler/replicate.go
  controllers/replicatectl/image_replicate_registry_job.go
  controllers/replicatectl/image_replicate_status.go
  controllers/replicatectl/image_replicate_subresource.go
  internal/schemes/image_replicate_job_scheme.go
  internal/schemes/util.go
  internal/utils/utils.go
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/registry/ext/dockerhub/util_test.go
  pkg/registry/replicate/copy.go
Labels: type: maintenance

#121 [mod] Make login secret with loginId, loginPassword in externalregistry
  api/v1/conditions.go
  api/v1/externalregistry_types.go
  config/crd/bases/tmax.io_externalregistries.yaml
  controllers/exregctl/external_registry_job.go
  controllers/exregctl/external_registry_secret.go
  controllers/exregctl/external_registry_status.go
  controllers/exregctl/handler/extreg_sync.go
  controllers/externalregistry_controller.go
  internal/schemes/external_registry_secret_scheme.go
  internal/schemes/util.go
  pkg/apiserver/apis/v1/scanrequest.go
  pkg/apiserver/apis/v1/scanresult.go
Labels: type: maintenance

#122 [doc] Add oneOf field in Registry CRD
  Makefile
  config/crd/bases/tmax.io_registries.yaml
  docs/dev.md
Labels: type: docs

#125 [fix] Change keyclock-secret trust to operator-rootca
  controllers/imagescanrequest_controller.go
Labels: type: maintenance

#126 [release] Bump up version to v0.2.4
  config/manager/manager.yaml
  docs/install.md
Labels: type: maintenance

#128 [fix] Check if client exists in keycloak
  api/v1/conditions.go
  controllers/keycloakctl/controller.go
  controllers/regctl/registry_status.go
  controllers/registry_controller.go
Labels: type: bug

#129 [mod] Able to sign in replicating image
  api/v1/conditions.go
  api/v1/imagereplicate_types.go
  config/crd/bases/tmax.io_imagereplicates.yaml
  controllers/imagereplicate_controller.go
  controllers/replicatectl/image_replicate_imagesignrequest.go
  controllers/replicatectl/image_replicate_registry_job.go
  controllers/replicatectl/image_replicate_status.go
  internal/schemes/image_replicate_imagesignrequest_scheme.go
  internal/schemes/util.go
  internal/utils/http.go
Labels: type: maintenance

#131 [doc] Add usage of image replicate
  api/v1/imagereplicate_types.go
  config/crd/bases/tmax.io_imagereplicates.yaml
  docs/README.md
  docs/usage/imagereplicate.md
Labels: type: docs

#132 [doc] Add installing job_manager in install script
  install.sh
  uninstall.sh
Labels: type: docs

#133 [release] Bump up version to v0.3.0
  config/manager/manager.yaml
  docs/install.md
Labels: type: minor

#134 [mod] Correct dockerhub auth url in external registry login secret
  internal/schemes/external_registry_secret_scheme.go
  internal/utils/k8s_utils.go
  pkg/image/image.go
Labels: type: maintenance

#135 [doc] Modify imagePullSecret field to loginId and loginPassword in external registry
  config/samples/tmax.io_v1_externalregistry.yaml
  docs/usage/externalregistry.md
Labels: type: docs

#136 [doc] Modify job manager yaml
  config/manager/job_manager.yaml
  config/manager/manager.yaml
  docs/install.md
  docs/usage/README.md
Labels: type: docs

#137 [mod] HarborV2 type image replicate is available
  api/v1/imagereplicate_types.go
  config/crd/bases/tmax.io_imagereplicates.yaml
  pkg/image/blob.go
  pkg/registry/ext/harbor/v2/client.go
  pkg/registry/factory.go
Labels: type: maintenance

#138 [mod] Able to replicate image without specified imagePullSecret
  Makefile
  api/v1/imagereplicate_types.go
  config/crd/bases/tmax.io_imagereplicates.yaml
  controllers/exregctl/external_registry_job.go
  controllers/replicatectl/handler/replicate.go
  controllers/replicatectl/image_replicate_imagesignrequest.go
  docs/usage/imagereplicate.md
  pkg/registry/base/interface.go
  pkg/registry/factory.go
Labels: type: docs, type: maintenance

#139 [mod] Synchronize after replicating image
  api/v1/conditions.go
  controllers/imagereplicate_controller.go
  controllers/replicatectl/image_replicate_imagesignrequest.go
  controllers/replicatectl/image_replicate_status.go
  controllers/replicatectl/image_replicate_sync_job.go
  internal/common/http/client.go
  internal/schemes/image_replicate_sync_job_scheme.go
  internal/schemes/util.go
  pkg/image/image.go
  pkg/registry/factory.go
Labels: type: maintenance

#140 [mod] Able to set notary cpu, memory spec
  api/v1/notary_types.go
  api/v1/registry_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_notaries.yaml
  config/crd/bases/tmax.io_registries.yaml
  controllers/regctl/registry_deployment.go
  internal/common/config/config.go
  internal/common/config/env.go
  internal/schemes/notary_db_pod_scheme.go
  internal/schemes/notary_scheme.go
  internal/schemes/notary_server_pod_scheme.go
  internal/schemes/notary_signer_pod_scheme.go
  internal/schemes/registry_deployment_scheme.go
Labels: type: maintenance

#141 [doc] Add notary resource setting in registry usage
  docs/usage/registry.md
Labels: type: docs
