Repository tmax-cloud/registry-operator, pull requests merged in 2021-02, with the labels that each got.

#81 [mod] Always trust internal keycloak ca in scanning image
  controllers/scanctl/registry_scan.go
  pkg/registry/registry.go
  pkg/scan/clair/reg.go
Labels: type: maintenance

#82 [doc] Modify guide to install specific version
  config/manager/manager.yaml
  docs/install.md
Labels: type: docs

#85 [fix] Failed to patch registry deployment
  controllers/regctl/registry_deployment.go
  internal/schemes/registry_deployment_scheme.go
Labels: type: bug

#86 [doc] Add resource usage
  api/v1/imagesignrequest_types.go
  api/v1/notary_types.go
  api/v1/registry_pvc_types.go
  api/v1/registry_types.go
  api/v1/repository_types.go
  config/crd/bases/tmax.io_imagesignrequests.yaml
  config/crd/bases/tmax.io_notaries.yaml
  config/crd/bases/tmax.io_registries.yaml
  config/crd/bases/tmax.io_repositories.yaml
  docs/usage/imagescanrequest.md
  docs/usage/imagesigner.md
  docs/usage/imagesignrequest.md
  docs/usage/registry.md
  docs/usage/repository.md
  docs/usage/usage_template.md
Labels: type: docs

#87 [fix] Fix a bug to be able to create imagesigner spec is empty
  pkg/apiserver/apis/v1/mutate.go
Labels: type: bug

#89 [mod] Add liveness, readiness, cpu, memory settings to registry deployment
  api/v1/errors.go
  api/v1/registry_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_registries.yaml
  controllers/regctl/registry_deployment.go
  internal/schemes/registry_deployment_scheme.go
  internal/utils/utils.go
Labels: type: maintenance

#84 [refactor] Modify deploying clair to use kustomize
  config/manager/clair/10-clair-deploy.yml
  config/manager/clair/20-clair-svc.yml
  config/manager/clair/30-clair-db-deploy.yml
  config/manager/clair/40-clair-db-svc.yml
  config/manager/clair/Makefile
  config/manager/clair/clair-config.yml
  config/manager/clair/kustomization.yaml
Labels: type: docs

#91 [doc] Modify installation guide and remove unnessary files.
  config/manager/clair.yaml
  config/manager/clair_config.yaml
  docs/install.md
  uninstall.sh
Labels: type: docs

#93 [feat] Add option for registry read-only
  api/v1/registry_types.go
  config/crd/bases/tmax.io_registries.yaml
  controllers/regctl/registry_deployment.go
  controllers/repository_gc.go
  docs/usage/registry.md
  docs/usage/repository.md
  internal/schemes/registry_deployment_scheme.go
Labels: type: feature

#95 [doc] Reduce warning and modify field description
  README.md
  api/v1/registry_types.go
  config/crd/bases/tmax.io_registries.yaml
  config/samples/tmax.io_v1_registry.yaml
  controllers/keycloakctl/controller.go
  controllers/regctl/registry_dcj_secret.go
  controllers/registry_controller.go
  docs/README.md
  docs/dev.md
  docs/envs.md
  docs/install.md
  docs/push.md
  docs/release.md
  docs/usage/README.md
  docs/usage/registry.md
  docs/usage/usage_template.md
  internal/schemes/registry_cert_secret_scheme.go
  internal/schemes/registry_dcj_secret_scheme.go
  registry/api.go
Labels: type: docs

#94 [mod] Update registry status reasonably
  controllers/notary_controller.go
  controllers/notaryctl/notary_status.go
  controllers/regctl/registry_status.go
  controllers/registry_controller.go
  internal/common/http/client.go
Labels: type: maintenance

#96 [fix] Synchronize same registry name in differenet namespace
  README.md
  internal/common/http/client.go
  registry/manager.go
Labels: type: bug

#98 [feat] Add External Registry
  PROJECT
  api/v1/externalregistry_types.go
  api/v1/registry_types.go
  api/v1/repository_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_externalregistries.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_externalregistries.yaml
  config/crd/patches/webhook_in_externalregistries.yaml
  config/manager/manager_config.yaml
  config/rbac/externalregistry_editor_role.yaml
  config/rbac/externalregistry_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/tmax.io_v1_externalregistry.yaml
  controllers/exregctl/external_registry_cronjob.go
  controllers/exregctl/external_registry_status.go
  controllers/exregctl/external_registry_subresource.go
  controllers/externalregistry_controller.go
  controllers/keycloakctl/client.go
  controllers/keycloakctl/controller.go
  controllers/registrycronjob_controller.go
  controllers/repoctl/registry_repository.go
  controllers/repository_controller.go
  controllers/repository_gc.go
  controllers/scanctl/registry_scan.go
  go.sum
  internal/common/config/config.go
  internal/common/config/env.go
  internal/common/http/client.go
  internal/schemes/external_registry_cron_job_scheme.go
  internal/schemes/registry_repository_scheme.go
  internal/schemes/util.go
  internal/utils/http.go
  internal/utils/k8s_utils.go
  internal/utils/utils.go
  main.go
  pkg/registry/ext/client.go
  pkg/registry/ext/factory/sync.go
  pkg/registry/ext/harbor/v2/api.go
  pkg/registry/ext/harbor/v2/client.go
  pkg/registry/ext/harbor/v2/types.go
  pkg/registry/registry.go
  pkg/registry/sync/sync.go
  pkg/scheduler/scheduler.go
  registry/api.go
Labels: type: feature

#99 [doc] Modify configmap as k8s object
  config/manager/manager_config.yaml
  install.sh
Labels: type: docs

#101 [fix] Add RegistryJob TTL collector
  api/v1/registryjob_types.go
  controllers/registryjob_controller.go
Labels: type: maintenance

#100 [feat] Exteral registry scanning
  docs/swagger-api.yaml
  pkg/apiserver/apis/v1/scanrequest.go
Labels: type: feature

#102 [mod] Modify external registry status
  api/v1/conditions.go
  api/v1/externalregistry_types.go
  api/v1/registry_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_externalregistries.yaml
  controllers/exregctl/external_registry_cronjob.go
  controllers/exregctl/external_registry_job.go
  controllers/exregctl/external_registry_status.go
  controllers/externalregistry_controller.go
  controllers/notaryctl/notary_status.go
  controllers/regctl/registry_status.go
  internal/schemes/external_registry_job_scheme.go
  internal/schemes/util.go
  internal/utils/utils.go
Labels: type: maintenance

#103 [doc] Add usage of external registry
  config/samples/tmax.io_v1_externalregistry.yaml
  docs/usage/README.md
  docs/usage/externalregistry.md
  docs/usage/registry.md
Labels: type: docs

#104 [feat] Add external registry's scanning result API
  pkg/apiserver/apis/v1/scanresult.go
Labels: type: feature

#105 [doc] Bump up version to v0.2.2
  config/manager/manager.yaml
  docs/install.md
Labels: type: docs

#106 [feat] Synchronize repository signer
  LICENCES/docker/cli/LICENSE
  LICENSE
  api/v1/externalregistry_types.go
  config/crd/bases/tmax.io_externalregistries.yaml
  go.mod
  go.sum
  main.go
  pkg/trust/helper.go
  pkg/trust/trust.go
  pkg/trust/types.go
  registry/manager.go
Labels: type: feature

#109 [fix] sycn repository list in pushing image
  server/registry_handler.go
Labels: type: bug

#111 [fix] Sycn repository list in pushing image
  server/registry_handler.go
Labels: type: bug

#112 Refactor/scan
  .gitignore
  api/v1/imagescanrequest_types.go
  controllers/imagescanrequest_controller.go
  controllers/scanctl/job.go
  controllers/scanctl/registry_scan.go
  controllers/scanctl/report.go
  controllers/scanctl/scan_worker.go
  controllers/scanctl/task.go
  internal/utils/k8s/secrethelper/imagepullsecret.go
  internal/utils/k8s/secrethelper/tlssecret.go
Labels: type: maintenance

#113 [feat] Replicate image between hypercloud registries
  PROJECT
  api/v1/imagereplicate_types.go
  api/v1/registry_types.go
  api/v1/repository_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_imagereplicates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_imagereplicates.yaml
  config/crd/patches/webhook_in_imagereplicates.yaml
  config/rbac/imagereplicate_editor_role.yaml
  config/rbac/imagereplicate_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/tmax.io_v1_imagereplicate.yaml
  controllers/imagereplicate_controller.go
  controllers/keycloakctl/client.go
  controllers/keycloakctl/controller.go
  go.mod
  internal/utils/http.go
  main.go
  manager/registry.go
  pkg/image/api.go
  pkg/image/blob.go
  pkg/image/catalog.go
  pkg/image/image.go
  pkg/image/image_named.go
  pkg/image/image_test.go
  pkg/image/manifest.go
  pkg/image/types.go
  pkg/registry/base/interface.go
  pkg/registry/base/store.go
  pkg/registry/base/types.go
  pkg/registry/ext/factory/sync.go
  pkg/registry/ext/harbor/v2/client.go
  pkg/registry/factory.go
  pkg/registry/inter/client.go
  pkg/registry/inter/factory/sync.go
  pkg/registry/registry.go
  pkg/registry/sync/sync.go
  pkg/scan/scan.go
Labels: type: feature

#114 [refactor] Modify scheduler for external injection
  api/v1/registryjob_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_registrycronjobs.yaml
  config/crd/bases/tmax.io_registryjobs.yaml
  config/samples/tmax.io_v1_registrycronjob.yaml
  config/samples/tmax.io_v1_registryjob.yaml
  controllers/exregctl/handler/extreg_sync.go
  controllers/externalregistry_controller.go
  internal/schemes/external_registry_cron_job_scheme.go
  internal/schemes/external_registry_job_scheme.go
  main.go
  pkg/scheduler/scheduler.go
Labels: type: maintenance
