Repository tmax-cloud/registry-operator, pull requests merged in 2021-01, with the labels that each got.

#28 [mod] Add release draft workflow job
  .github/release-drafter-config.yml
  .github/workflows/cicd.yaml
Labels: type: maintenance

#29 [mod] Delete duplicated processing workflow job on PR
  .github/workflows/cicd.yaml
  .github/workflows/draft.yaml
Labels: type: maintenance

#27 [feat] Add image-scan api
  PROJECT
  api/v1/imagescanrequest_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_imagescanrequests.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_imagescanrequests.yaml
  config/crd/patches/webhook_in_imagescanrequests.yaml
  config/manager/manager.yaml
  config/manager/manager_dev.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/tmax.io_v1_imagescanrequest.yaml
  controllers/imagescanrequest_controller.go
  controllers/scanctl/registry_scan.go
  go.mod
  go.sum
  main.go
Labels: type: feature

#30 [mod] Add deployment options and delete volumemode
  api/v1/registry_pvc_types.go
  api/v1/registry_types.go
  config/crd/bases/tmax.io_notaries.yaml
  config/crd/bases/tmax.io_registries.yaml
  config/samples/create_pvc_registry.yaml
  config/samples/default_registry.yaml
  config/samples/exist_pvc_registry.yaml
  config/samples/ingress_registry.yaml
  config/samples/tmax.io_v1_notary.yaml
  config/samples/tmax.io_v1_registry.yaml
  internal/schemes/notary_db_pvc_scheme.go
  internal/schemes/registry_deployment_scheme.go
  internal/schemes/registry_pvc_scheme.go
Labels: type: maintenance

#31 [mod] Update init status of image-sign-request
  api/v1/imagesignrequest_types.go
  controllers/imagesignrequest_controller.go
  controllers/status.go
Labels: type: maintenance

#32 [mod] Add printcolumns to crds
  api/v1/imagescanrequest_types.go
  api/v1/imagesigner_types.go
  api/v1/imagesignrequest_types.go
  api/v1/notary_types.go
  api/v1/registry_types.go
  api/v1/repository_types.go
  api/v1/signerkey_types.go
  config/crd/bases/tmax.io_imagescanrequests.yaml
  config/crd/bases/tmax.io_imagesigners.yaml
  config/crd/bases/tmax.io_imagesignrequests.yaml
  config/crd/bases/tmax.io_notaries.yaml
  config/crd/bases/tmax.io_registries.yaml
  config/crd/bases/tmax.io_repositories.yaml
  config/crd/bases/tmax.io_signerkeys.yaml
Labels: type: docs

#33 [fix] Delete notaryURL's port 443 in ingress type registry
  controllers/notaryctl/notary_server_ingress.go
Labels: type: bug

#34 [mod] Add env to set private registry
  api/v1/registry_types.go
  config/crd/bases/tmax.io_registries.yaml
  config/manager/manager.yaml
  config/manager/manager_dev.yaml
  controllers/regctl/registry_deployment.go
  internal/schemes/notary_db_pod_scheme.go
  internal/schemes/notary_server_pod_scheme.go
  internal/schemes/notary_signer_pod_scheme.go
  internal/schemes/registry_deployment_scheme.go
  internal/utils/config.go
  main.go
Labels: type: maintenance

#35 [mod] Modify release condition
  .github/workflows/cicd.yaml
  .github/workflows/draft.yaml
Labels: type: maintenance

#36 [doc] Modify comment for crds
  api/v1/imagesigner_types.go
  api/v1/imagesignrequest_types.go
  api/v1/registry_pvc_types.go
  api/v1/registry_types.go
  config/crd/bases/tmax.io_imagesigners.yaml
  config/crd/bases/tmax.io_imagesignrequests.yaml
  config/crd/bases/tmax.io_notaries.yaml
  config/crd/bases/tmax.io_registries.yaml
Labels: type: docs

#37 [mod] add crd comment
  api/v1/imagescanrequest_types.go
  config/crd/bases/tmax.io_imagescanrequests.yaml
Labels: type: docs

#40 [fix] Remove certificate's pem block incorrectly
  controllers/keycloakctl/controller.go
  controllers/registry_controller.go
  internal/utils/cert.go
Labels: type: bug

#41 [fix] Fix backup logfile directory
  internal/common/operatorlog/log.go
Labels: type: bug

#39 [feat] Added singer policy type
  api/v1/signerpolicy_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_signerpolicies.yaml
Labels: type: feature

#42 [feat] Add cluster name for multi cluster
  config/manager/manager.yaml
  config/manager/manager_dev.yaml
  controllers/keycloakctl/controller.go
Labels: type: feature

#43 [doc] Modify test-crd for added crds
  Makefile
  config/crd/bases/tmax.io_imagescanrequests.yaml
Labels: type: docs

#44 fix SignerPolicy type to add DeepCopyObject
  api/v1/signerpolicy_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_signerpolicies.yaml
Labels: type: maintenance

#46 [mod] Set default summary value
  controllers/scanctl/registry_scan.go
Labels: type: maintenance

#45 [mod] Encode signer key by base64
  api/v1/signerkey_types.go
  pkg/controllers/controller.go
  pkg/trust/trust.go
Labels: type: maintenance

#47 fix signerpolicy to define shortname
  api/v1/signerpolicy_types.go
  config/crd/bases/tmax.io_signerpolicies.yaml
Labels: type: maintenance

#51 [feat] Scan multi images
  api/v1/imagescanrequest_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_imagescanrequests.yaml
  config/samples/tmax.io_v1_imagescanrequest.yaml
  controllers/imagescanrequest_controller.go
  controllers/repoctl/registry_repository.go
  controllers/scanctl/registry_scan.go
  internal/harbor/registry.go
  internal/utils/image.go
  internal/utils/k8s_utils.go
  pkg/apiserver/apis/v1/apis.go
  pkg/apiserver/apis/v1/authorize.go
  pkg/apiserver/apis/v1/imagesignrequest.go
  pkg/apiserver/apis/v1/mutate.go
  pkg/apiserver/apis/v1/scanrequest.go
  pkg/apiserver/apis/v1/scanresult.go
  pkg/apiserver/apis/v1/signer.go
  pkg/scan/scan.go
  pkg/scan/scan_test.go
  pkg/trust/image.go
  pkg/trust/trust.go
Labels: type: feature

#53 [fix] Add scan request name path for request api
  pkg/apiserver/apis/v1/scanrequest.go
Labels: type: bug

#54 [fix] Fix tag wildcard bug
  pkg/apiserver/apis/v1/scanrequest.go
Labels: type: bug

#55 [fix] Fix scan request credential bug
  pkg/apiserver/apis/v1/scanrequest.go
Labels: type: bug

#52 [feat] add clair install guide
  README.md
  config/manager/clair.yaml
  config/manager/clair_config.yaml
Labels: type: docs

#56 [fix] Fix scan results api logic
  pkg/apiserver/apis/v1/apis.go
  pkg/apiserver/apis/v1/scanrequest.go
  pkg/apiserver/apis/v1/scanresult.go
  pkg/scan/scan.go
  pkg/trust/image.go
Labels: type: bug

#58 [mod] Scan any registry not only internal registry
  api/v1/imagescanrequest_types.go
  config/crd/bases/tmax.io_imagescanrequests.yaml
  controllers/scanctl/registry_scan.go
  go.mod
  internal/common/http/client.go
  pkg/registry/registry.go
  pkg/scan/clair/reg.go
Labels: type: maintenance

#62 [mod] Send more detail data to ES
  api/v1/imagescanrequest_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_imagescanrequests.yaml
  controllers/imagescanrequest_controller.go
  controllers/scanctl/registry_scan.go
  main.go
  pkg/registry/registry.go
Labels: type: maintenance

#63 [fix] Repository is not deleted in synchronizing all registry
  controllers/keycloakctl/client.go
  main.go
  registry/manager.go
Labels: type: bug

#64 [mod] Set env with manager_config.yaml file
  README.md
  config/manager/keycloak_secret.yaml
  config/manager/manager.yaml
  config/manager/manager_config.yaml
  config/manager/manager_dev.yaml
  config/pki/default_keycloak.crt
  controllers/imagescanrequest_controller.go
  controllers/imagesignrequest_controller.go
  controllers/keycloakctl/client.go
  controllers/keycloakctl/controller.go
  controllers/regctl/registry_deployment.go
  controllers/regctl/registry_notary.go
  controllers/scanctl/registry_scan.go
  docs/envs.md
  go.mod
  install.sh
  internal/common/certs/rootca.go
  internal/common/certs/util.go
  internal/common/config/config.go
  internal/harbor/registry.go
  internal/schemes/notary_db_pod_scheme.go
  internal/schemes/notary_server_pod_scheme.go
  internal/schemes/notary_signer_pod_scheme.go
  internal/schemes/registry_deployment_scheme.go
  internal/schemes/util.go
  internal/utils/config.go
  main.go
  pkg/scan/scan.go
Labels: type: maintenance

#65 [doc] Modify printcolumn of registry crd
  api/v1/registry_types.go
  config/crd/bases/tmax.io_registries.yaml
Labels: type: docs

#66 [doc] Add image push guide
  docs/push.md
Labels: type: docs

#67 [doc] Modify install script
  config/manager/manager.yaml
  config/manager/manager_dev.yaml
  install.sh
Labels: type: docs

#68 [mod] Modify base image from alpine to distroless
  Dockerfile
  config/manager/manager.yaml
  config/manager/manager_dev.yaml
Labels: type: docs

#69 [doc] Add env and config mapping table
  README.md
  docs/envs.md
Labels: type: docs, type: minor

#71 disable setDebug of restyClient to reduce duplicate logs
  controllers/keycloakctl/controller.go
Labels: type: maintenance

#74 [fix] Fix a bug to get default image
  controllers/regctl/registry_deployment.go
Labels: type: bug

#73 [mod] Watch config file and update configuration
  config/manager/manager_config.yaml
  go.mod
  internal/common/config/config.go
  internal/utils/config.go
  main.go
Labels: type: maintenance

#76 [doc] Add uninstall script and guide
  README.md
  config/samples/tmax.io_v1_registry.yaml
  docs/README.md
  docs/dev.md
  docs/install.md
  docs/push.md
  docs/release.md
  install.sh
  uninstall.sh
Labels: type: docs

#77 [fix] Verify registry's server urls when signing
  controllers/imagesignrequest_controller.go
Labels: type: bug

#78 [doc] Modify guide to push image
  docs/push.md
Labels: type: docs

#75 deleted signer policy crd
  api/v1/signerpolicy_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/tmax.io_signerpolicies.yaml
Labels: type: maintenance
