Repository tmax-cloud/registry-operator, pull requests merged in 2021-04, with the labels that each got.

#142 [refactor] create registry subresource concurrently
  api/v1/errors.go
  controllers/regctl/registry_cert_secret.go
  controllers/regctl/registry_configmap.go
  controllers/regctl/registry_dcj_secret.go
  controllers/regctl/registry_deployment.go
  controllers/regctl/registry_ingress.go
  controllers/regctl/registry_notary.go
  controllers/regctl/registry_pod.go
  controllers/regctl/registry_pvc.go
  controllers/regctl/registry_service.go
  controllers/regctl/registry_subresource.go
  controllers/registry_controller.go
  internal/utils/utils.go
Labels: type: maintenance

#143 [fix] Bug deleting images if error occurs in synchronizing
  controllers/repository_gc.go
  internal/common/certs/rootca.go
  pkg/image/catalog.go
  pkg/image/image.go
  pkg/registry/ext/docker/client.go
  pkg/registry/inter/client.go
Labels: type: bug

#145 [fix] Fix synchronize error for external registry
  internal/schemes/util.go
  pkg/registry/ext/dockerhub/client.go
  pkg/registry/ext/harbor/v2/client.go
  pkg/registry/inter/client.go
Labels: type: bug

#146 Bump up version to tmaxcloudck/notary_mysql:0.6.2-rc2
  config/manager/job_manager.yaml
  config/manager/manager.yaml
  config/manager/manager_config.yaml
  docs/README.md
  docs/envs.md
  docs/install.md
  internal/common/config/config.go
Labels: type: docs

#148 Fix/scan - IMS 260172
  controllers/imagescanrequest_controller.go
  internal/utils/k8s/secrethelper/imagepullsecret.go
Labels: type: bug
